---
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    # there is no reason to test external files
    - "roles.galaxy/**/*"
    - "vendor/**/*"
    - "tests/integration/**/roles/*"
    - "extra_roles/**/*"
    - "qansible"
  # enable detailed explanations available in cops
  # the default output is not enough to understand what is wrong
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true

  # the default CacheRootDirectory is no longer `/tmp`, but a directory under
  # `$HOME` and some Unix platforms use symlink to that path
  AllowSymlinksInCacheRootDirectory: true

Style/StringLiterals:
  # https://github.com/reallyenglish/ansible-role-example/issues/60#issuecomment-280573231
  EnforcedStyle: double_quotes

Style/SymbolArray:
  # perefer brackets for `grep-ability`
  EnforcedStyle: brackets

Metrics/BlockLength:
  ExcludedMethods:
    # these two exclude long blocks in `_spec.rb`
    - describe
    - context

Layout/LineLength:
  Exclude:
    # Gemfile is not application code
    - "Gemfile"
    - "*.gemspec"
  # ignore heredoc for readability
  AllowHeredoc: true
  # URLs are almost always long
  AllowURI: true
  URISchemes:
    - http
    - https
    - git
    - ftp
  IgnoreCopDirectives: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
